"""Configuration paths and constants for the Solarys backend."""
from pathlib import Path

# Project root = parent of `backend/`
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

# Models directory
MODELS_INPUT_DIR = PROJECT_ROOT / "models_input"

# ───────── Module 01 — Bill analysis (Qwen2-VL fine-tune + solar agent) ─────────
BILL_DIR = MODELS_INPUT_DIR / "01_bill_analysis" / "solar-ai-project"
BILL_HF_MODEL = "chtibawi/qwen-bill-model"   # colleague's fine-tune on HuggingFace

# ───────── Module 02 — Rooftop segmentation ─────────
ROOFTOP_EXPORT_DIR = (
    MODELS_INPUT_DIR
    / "02_rooftop_segmentation"
    / "export_rooftop-20260428T231533Z-3-001"
    / "export_rooftop"
)
ROOFTOP_MODEL_PATH = ROOFTOP_EXPORT_DIR / "unet_rooftop.keras"
ROOFTOP_META_PATH = ROOFTOP_EXPORT_DIR / "meta.json"
ROOFTOP_SAMPLES_DIR = ROOFTOP_EXPORT_DIR / "samples"

# ───────── Module 04 — ELPV Binary classification ─────────
PANEL_BINARY_DIR = (
    MODELS_INPUT_DIR
    / "04_elpv_binary"
    / "binary classification"
    / "binary_mobilenetv3"
)
PANEL_BINARY_MODEL = PANEL_BINARY_DIR / "model.pt"   # TorchScript
PANEL_BINARY_META  = PANEL_BINARY_DIR / "meta.json"

# ───────── Module 05 — ELPV Multi-class defect type ─────────
PANEL_MULTICLASS_DIR = (
    MODELS_INPUT_DIR
    / "05_elpv_multiclass"
    / "multiclassification"
    / "multiclass_efficientnet_full"
)
PANEL_MULTICLASS_MODEL = PANEL_MULTICLASS_DIR / "model.pt"   # TorchScript
PANEL_MULTICLASS_META  = PANEL_MULTICLASS_DIR / "meta.json"

# ───────── Module 03 — Defect localization (Swin-T + GradCAM) ─────────
PANEL_DETECTION_DIR = (
    MODELS_INPUT_DIR
    / "03_el_object_detection"
    / "solar_defect_model"
    / "solar_defect_model"
    / "bloc_A"
)
PANEL_DETECTION_MODEL = PANEL_DETECTION_DIR / "swin_best_model.pth"   # state_dict
PANEL_DETECTION_META  = PANEL_DETECTION_DIR / "meta.json"

# ───────── Module 06 — Battery SoH (Fusion Model V2) ─────────
BATTERY_DIR = (
    MODELS_INPUT_DIR
    / "06_battery_soh"
    / "fusion_model_v2versionfinal"
    / "fusion_model_v2versionfinal"
)
BATTERY_MODEL_PATH = BATTERY_DIR / "model" / "fusion_model_v2 (1).pth"
BATTERY_SCALER_PATH = BATTERY_DIR / "model" / "scaler_v2.pkl"
BATTERY_FEATURE_COLS_PATH = BATTERY_DIR / "model" / "feature_cols_v2.pkl"
BATTERY_META_PATH = BATTERY_DIR / "metadata" / "meta.json"
BATTERY_SAMPLES_DIR = BATTERY_DIR / "samples" / "testmaram (2)" / "testmaram"

# ───────── Module 07 — Solar Ramp Forecasting (ResNet18 + GRU multimodal) ─────────
RAMP_DIR = (
    MODELS_INPUT_DIR
    / "07_solar_ramp"
    / "Short-Term Solar Ramp Forecasting"
    / "Short-Term Solar Ramp Forecasting"
)
RAMP_MODEL_PATH = RAMP_DIR / "multitask_ramp_v2_resnet_gru.pth"
RAMP_SCALER_PATH = RAMP_DIR / "multitask_ramp_v2_scaler.pkl"
RAMP_META_PATH = RAMP_DIR / "meta.json"
RAMP_TEST_SAMPLES_PATH = RAMP_DIR / "test_samples.json"
RAMP_SAMPLES_DIR = RAMP_DIR / "bundled_samples"   # generated by script (deprecated demos)
RAMP_DEPLOYMENT_DIR = (
    RAMP_DIR / "deployment_test_inputs" / "deployment_test_inputs"
)   # real deployment test inputs from colleague — 5 samples with PNG + CSV + GT

# CORS — allow Vite dev server
ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
